apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: app
          image: flask-app:latest
          imagePullPolicy: IfNotPresent
          ports:
          -  containerPort: 5000